version: '3'
services:
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092

  zookeeper:
    image: bitnami/zookeeper
    ports:
      - "2181:2181"

  redis:
    image: redis

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  api:
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    depends_on: [kafka, redis, db]

  worker:
    build: .
    command: celery -A tasks.celery_tasks worker --loglevel=info
    depends_on: [redis, db]

  consumer:
    build: .
    command: python consumers/kafka_consumer.py
    depends_on: [kafka, worker]